site_name: InGate
site_url: https://kubernetes-sigs.github.io/ingate

repo_name: kubernetes-sigs/ingate
repo_url: https://github.com/kubernetes-sigs/ingate

theme:
  name: material

  palette:
    primary: indigo
    scheme: slate
    accent: light green

  include_sidebar: true

nav:
  - Welcome: index.md
  - Contributing: 
      - Getting Started: contributing/contributing.md
      - Contributor Ladder: contributing/ladder.md
  - FAQ: faq.md
