version: "2"

run:
  timeout: 10m
  allow-parallel-runners: true

issues:
  # Maximum issues count per one linter. Set to 0 to disable. Default is 50.
  max-issues-per-linter: 0

  # Maximum count of issues with the same text. Set to 0 to disable. Default is 3.
  max-same-issues: 0
linters:
  default: none
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - contextcheck
    - copyloopvar
    - decorder
    - dogsled
    - dupl
    - durationcheck
    - errcheck
    - errchkjson
    - errname
    - fatcontext
    - ginkgolinter
    - gocheckcompilerdirectives
    - goconst
    - gocritic
    - gocyclo
    - godox
    - goheader
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - govet
    - grouper
    - importas
    - ineffassign
    - intrange
    - loggercheck
    - makezero
    - mirror
    - misspell
    - musttag
    - nakedret
    - nolintlint
    - nosprintfhostport
    - perfsprint
    - prealloc
    - predeclared
    - promlinter
    - reassign
    - revive
    - rowserrcheck
    - sloglint
    - sqlclosecheck
    - staticcheck
    - tagalign
    - testableexamples
    - testifylint
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - whitespace
    - zerologlint
  settings:
    gocyclo:
      min-complexity: 40
    godox:
      keywords:
        - BUG
        - FIXME
        - HACK
    errcheck:
      check-type-assertions: true
      check-blank: true
    nolintlint:
      # Enable to ensure that nolint directives are all used. Default is true.
      allow-unused: false
      # Exclude following linters from requiring an explanation.  Default is [].
      allow-no-explanation: []
      # Enable to require an explanation of nonzero length after each nolint directive. Default is false.
      # TODO(lint): Enforce explanations for `nolint` directives
      require-explanation: false
      # Enable to require nolint directives to mention the specific linter being suppressed. Default is false.
      require-specific: true

formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
